# Generated by Django 3.1.4 on 2021-04-20 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 55, 29, 201362), verbose_name='date published'),
        ),
    ]
