# Generated by Django 3.1.4 on 2021-04-20 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210420_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 11, 17, 30, 431201), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(max_length=200),
        ),
    ]
