# Generated by Django 3.1.4 on 2021-04-20 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210420_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 13, 9, 55, 631909), verbose_name='date published'),
        ),
    ]
