# Generated by Django 3.1.4 on 2021-04-22 04:24

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210420_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 10, 9, 17, 463805), verbose_name='date published'),
        ),
    ]
